baseURL = 'https://scidsg.github.io/ddosecrets-redesign/'
languageCode = 'en-us'
title = 'DDoSecrets Wiki'

[frontmatter]
  lastmod = ['lastmod', ':git', ':fileModTime', ':default']

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10